# Import Libraries

In [86]:
# Import libraries
import pandas as pd
import numpy as np
import zipfile
import os

# Library options

In [55]:
# Library options
pd.set_option("display.max_columns", 500)

# Gather

Extract the zip file and load all its content that needed

## File Names

In [56]:
# Zip name
zip_name = "womens-ecommerce-clothing-reviews.zip"

In [57]:
# Csv file names
csv_name = "Womens Clothing E-Commerce Reviews.csv"

## Zip Content

In [58]:
# Old zip content
old_zip_content = [csv_name]

In [59]:
# zip content
current_zip_content = []

## Extract Zip File

In [60]:
# Extract zip and collect it's content names
with zipfile.ZipFile(zip_name) as _zip:
    _zip.extractall()
    current_zip_content = _zip.namelist()

## Load CSV Files

Load csv files as dataframes

In [61]:
# load csv files
df = pd.read_csv(csv_name)

## Test

Now let's see if the current zip file concent is the same when this document has been last updated. True is the good return value.

In [62]:
# Compare old and current content
old_zip_content == current_zip_content

True

# Assess & Clean

## Copy the original DataFrames

In [63]:
# Copy dataframes
df_clean = df.copy()

## Assess

In [64]:
df_clean

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
5,5,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
6,6,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits
7,7,858,39,"Shimmer, surprisingly goes with lots","I ordered this in carbon for store pick up, an...",4,1,4,General Petite,Tops,Knits
8,8,1077,24,Flattering,I love this dress. i usually get an xs but it ...,5,1,0,General,Dresses,Dresses
9,9,1077,34,Such a fun dress!,"I'm 5""5' and 125 lbs. i ordered the s petite t...",5,1,0,General,Dresses,Dresses
10,10,1077,53,Dress looks like it's made of cheap material,Dress runs small esp where the zipper area run...,3,0,14,General,Dresses,Dresses
11,11,1095,39,NaN,This dress is perfection! so pretty and flatte...,5,1,2,General Petite,Dresses,Dresses
12,12,1095,53,Perfect!!!,More and more i find myself reliant on the rev...,5,1,2,General Petite,Dresses,Dresses
13,13,767,44,Runs big,Bought the black xs to go under the larkspur m...,5,1,0,Initmates,Intimate,Intimates
14,14,1077,50,Pretty party dress with some issues,This is a nice choice for holiday gatherings. ...,3,1,1,General,Dresses,Dresses
15,15,1065,47,"Nice, but not for my body",I took these out of the package and wanted the...,4,1,3,General,Bottoms,Pants
16,16,1065,34,"You need to be at least average height, or taller",Material and color is nice. the leg opening i...,3,1,2,General,Bottoms,Pants
17,17,853,41,Looks great with white pants,Took a chance on this blouse and so glad i did...,5,1,0,General,Tops,Blouses
18,18,1120,32,Super cute and cozy,"A flattering, super cozy coat. will work well...",5,1,0,General,Jackets,Outerwear
19,19,1077,47,Stylish and comfortable,I love the look and feel of this tulle dress. ...,5,1,0,General,Dresses,Dresses
20,20,847,33,"Cute, crisp shirt","If this product was in petite, i would get the...",4,1,2,General,Tops,Blouses
21,21,1080,55,I'm torn!,"I'm upset because for the price of the dress, ...",4,1,14,General,Dresses,Dresses
22,22,1077,31,Not what it looks like,"First of all, this is not pullover styling. th...",2,0,7,General,Dresses,Dresses
23,23,1077,34,"Like it, but don't love it.",Cute little dress fits tts. it is a little hig...,3,1,0,General,Dresses,Dresses
24,24,847,55,Versatile,"I love this shirt because when i first saw it,...",5,1,0,General,Tops,Blouses
25,25,697,31,Falls flat,"Loved the material, but i didnt really look at...",3,0,0,Initmates,Intimate,Lounge
26,26,949,33,Huge disappointment,I have been waiting for this sweater coat to s...,2,0,0,General,Tops,Sweaters
27,27,1003,31,"Loved, but returned",The colors weren't what i expected either. the...,4,1,0,General,Bottoms,Skirts
28,28,684,53,Great shirt!!!,I have several of goodhyouman shirts and i get...,5,1,2,Initmates,Intimate,Lounge
29,29,4,28,Great layering piece,This sweater is so comfy and classic - it bala...,5,1,0,General,Tops,Sweaters
...,...,...,...,...,...,...,...,...,...,...,...
23456,23456,1104,35,Flattering and lovely sweater dress,I have been on a search for a dress with sleev...,5,1,3,General Petite,Dresses,Dresses
23457,23457,262,49,Adorable,"These pants are soft, fun print and comfy. the...",5,1,3,General Petite,Intimate,Lounge
23458,23458,862,63,NaN,This is my new favorite sweater. it is lightwe...,5,1,0,General Petite,Tops,Knits
23459,23459,1094,57,Perfect except slip,This is my new favorite dress! my only complai...,4,1,3,General Petite,Dresses,Dresses
23460,23460,1078,34,Such high hopes!,I purchased this for a very good price and i t...,3,0,0,General,Dresses,Dresses
23461,23461,262,49,Comfortable but not super-flattering on me,I tried these on at the store and the fit was ...,4,1,1,General Petite,Intimate,Lounge
23462,23462,999,24,Its okay,The pattern of this skirt is adorable and look...,3,1,0,General,Bottoms,Skirts
23463,23463,262,65,Comfy pants,"These pants overall are very comfortable, but ...",4,1,1,General Petite,Intimate,Lounge
23464,23464,1104,42,Compliments,I wore this dress to work the other day and go...,5,1,3,General Petite,Dresses,Dresses
23465,23465,1078,41,Falls nicely,I bought this dress for work and post work hap...,5,1,0,General,Dresses,Dresses
23466,23466,1104,34,Cute and comfy,This dress has a great design and fits very we...,4,1,0,General Petite,Dresses,Dresses
23467,23467,1104,60,Super flattering!,"I worry when i have an elastic waist, or somet...",5,1,23,General Petite,Dresses,Dresses
23468,23468,721,35,Sweet stripes,I love this little chemise! the adjustable str...,5,1,3,General Petite,Intimate,Lounge
23469,23469,262,50,Comfy and cute,My size was not available so based on reviews ...,4,1,0,General Petite,Intimate,Lounge
23470,23470,1104,39,NaN,NaN,5,1,0,General Petite,Dresses,Dresses
23471,23471,262,31,Awkward fit for me,"Love the way these pants look in the pictures,...",4,1,0,General Petite,Intimate,Lounge
23472,23472,855,32,Perfectly drapey,I saw the shirt on the retailer website and ne...,5,1,0,General,Tops,Knits
23473,23473,1104,29,Perfect dress,Great quality and extremely flattering. bonus ...,5,1,1,General Petite,Dresses,Dresses
23474,23474,1104,32,Much better in person!,"Yes, this is a great dress! i wasn't sure abou...",5,1,0,General Petite,Dresses,Dresses
23475,23475,1104,41,Cute dress,Cute dress but not for me. the waist is too h...,3,1,0,General Petite,Dresses,Dresses
23476,23476,522,27,Cheeky!,These bottoms are very cute but defiantly chee...,4,1,0,Initmates,Intimate,Swim
23477,23477,1094,39,Entrancing,I'm so impressed with the beautiful color comb...,4,1,5,General Petite,Dresses,Dresses
23478,23478,1104,32,Unflattering,I was surprised at the positive reviews for th...,1,0,0,General Petite,Dresses,Dresses
23479,23479,1005,42,What a fun piece!,So i wasn't sure about ordering this skirt bec...,5,1,0,General Petite,Bottoms,Skirts
23480,23480,862,35,NaN,NaN,5,1,0,General Petite,Tops,Knits
23481,23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses
23482,23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits
23483,23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses
23484,23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses
23485,23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses

## Issue Description

Replace missing values with "None"

## Cleaning Code

In [65]:
# Fill NaN with None
df_clean = df_clean.fillna("None")

## Test

In [66]:
df_clean.head(15)

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,None,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,None,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
5,5,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
6,6,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits
7,7,858,39,"Shimmer, surprisingly goes with lots","I ordered this in carbon for store pick up, an...",4,1,4,General Petite,Tops,Knits
8,8,1077,24,Flattering,I love this dress. i usually get an xs but it ...,5,1,0,General,Dresses,Dresses
9,9,1077,34,Such a fun dress!,"I'm 5""5' and 125 lbs. i ordered the s petite t...",5,1,0,General,Dresses,Dresses
10,10,1077,53,Dress looks like it's made of cheap material,Dress runs small esp where the zipper area run...,3,0,14,General,Dresses,Dresses
11,11,1095,39,None,This dress is perfection! so pretty and flatte...,5,1,2,General Petite,Dresses,Dresses
12,12,1095,53,Perfect!!!,More and more i find myself reliant on the rev...,5,1,2,General Petite,Dresses,Dresses
13,13,767,44,Runs big,Bought the black xs to go under the larkspur m...,5,1,0,Initmates,Intimate,Intimates
14,14,1077,50,Pretty party dress with some issues,This is a nice choice for holiday gatherings. ...,3,1,1,General,Dresses,Dresses

## Assess

## Issue Description

Change the undescriptive and the little misleading column headers. And make them
- "Unnamed: 0" to Review ID
- "Positive Feedback Count" to "Review Postitive Feedback Count"
- "Recommended IND" to "Recommended by Customer"

## Cleaning Code

In [67]:
# Rename columns
df_clean.rename(columns =
               {
                   "Unnamed: 0" : "Review ID",
                   "Positive Feedback Count" : "Review Postitive Feedback Count",
                   "Recommended IND" : "Recommended by Customer",
               }, inplace = True)

## Test

In [68]:
df_clean.head()

,Review ID,Clothing ID,Age,Title,Review Text,Rating,Recommended by Customer,Review Postitive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,None,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,None,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

## Assess

In [69]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
Review ID                          23486 non-null int64
Clothing ID                        23486 non-null int64
Age                                23486 non-null int64
Title                              23486 non-null object
Review Text                        23486 non-null object
Rating                             23486 non-null int64
Recommended by Customer            23486 non-null int64
Review Postitive Feedback Count    23486 non-null int64
Division Name                      23486 non-null object
Department Name                    23486 non-null object
Class Name                         23486 non-null object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

There are duplicated reviews texts, but they are written to different clothes. So these are not duplicated rows.

In [70]:
df_clean[(df_clean.duplicated("Review Text", keep = False)) & (df_clean["Review Text"] != "None")]

,Review ID,Clothing ID,Age,Title,Review Text,Rating,Recommended by Customer,Review Postitive Feedback Count,Division Name,Department Name,Class Name
1891,1891,1081,42,"Beautiful dress, fits poorly",I purchased this and another eva franco dress ...,2,0,5,General,Dresses,Dresses
7639,7639,1166,26,Love retailer bathing suits!,Perfect fit and i've gotten so many compliment...,5,1,1,Initmates,Intimate,Swim
9447,9447,1022,37,None,"Love, love these jeans. being short they come ...",5,1,0,General,Bottoms,Jeans
10067,10067,1171,26,Love retailer bathing suits!,Perfect fit and i've gotten so many compliment...,5,1,0,Initmates,Intimate,Swim
10137,10137,872,43,Love this shirt!,I bought this shirt at the store and after goi...,5,1,0,General Petite,Tops,Knits
10708,10708,632,60,Cute cover-up or summer top & shorts!,"Lightweight, soft cotton top and shorts. i thi...",5,1,8,Initmates,Intimate,Lounge
11074,11074,628,60,Cute cover-up or summer top & shorts!,"Lightweight, soft cotton top and shorts. i thi...",5,1,2,Initmates,Intimate,Lounge
12526,12526,1081,42,"Beautiful dress, fits horribly",I purchased this and another eva franco dress ...,2,0,3,General,Dresses,Dresses
13354,13354,393,26,Love retailer bathing suits!,Perfect fit and i've gotten so many compliment...,5,1,0,Initmates,Intimate,Swim
14275,14275,879,43,Love this shirt,I bought this shirt at the store and after goi...,5,1,0,General Petite,Tops,Knits
16988,16988,993,60,Soft & beautiful!,The sweater and skirt are so pretty! they're r...,5,1,1,General,Bottoms,Skirts
21470,21470,895,60,Soft & beautiful!,The sweater and skirt are so pretty! they're r...,5,1,5,General Petite,Tops,Fine gauge
21888,21888,1022,37,None,"Love, love these jeans. being short they come ...",5,1,0,General,Bottoms,Jeans

In [71]:
df_clean.sample(50)

,Review ID,Clothing ID,Age,Title,Review Text,Rating,Recommended by Customer,Review Postitive Feedback Count,Division Name,Department Name,Class Name
2807,2807,1099,51,Simple summer style,A perfect little simple style summer dress jus...,5,1,0,General Petite,Dresses,Dresses
7311,7311,1022,31,"Runs small, too much distressing","I have a few pairs of the stevie ankle, so i t...",3,0,4,General,Bottoms,Jeans
1066,1066,864,35,None,Cute and comfy shirt! tts- got my usual m (i'm...,5,1,0,General,Tops,Knits
12079,12079,985,32,So comfy and stylish!,I bought this for myself and my mom and we bot...,5,1,0,General,Jackets,Jackets
11077,11077,831,49,Better in person,I probably would have never purchased this blo...,4,1,0,General Petite,Tops,Blouses
17664,17664,840,21,Cute!,"The shirt is a very cute cut. it ""poofed"" out ...",4,1,1,General,Tops,Blouses
11977,11977,829,66,Wonderful!,This is a great blouse. the fabric is a fine r...,5,1,1,General Petite,Tops,Blouses
11137,11137,575,25,Better than i'd hoped,I saw this online yesterday and i was in the s...,5,1,3,General,Trend,Trend
369,369,895,39,Positively agree,All the rave reviews are true! this vest is p...,5,1,0,General Petite,Tops,Fine gauge
4057,4057,860,46,None,None,5,1,0,General Petite,Tops,Knits
8780,8780,936,43,Really pretty,Really pretty. not very itchy and a great swea...,4,1,0,General Petite,Tops,Sweaters
17360,17360,1059,36,Great pants!,These pants are a great addition to my work wa...,5,1,3,General,Bottoms,Pants
13609,13609,1095,55,Simple and beautiful,Unusual design and striking color make this th...,5,1,1,General Petite,Dresses,Dresses
7690,7690,867,37,"Beautiful fabric, very casual",This is a beautiful sweatshirt. that is a sent...,4,1,2,General,Tops,Knits
8329,8329,1103,47,Change armpits,"I love, love this dress except for the armpits...",4,1,0,General,Dresses,Dresses
13085,13085,1094,37,Meh,I tried this dress at the store and it made me...,3,0,1,General,Dresses,Dresses
22781,22781,1110,30,Proportions are off,I really liked the color and style of this dre...,3,0,1,General,Dresses,Dresses
9949,9949,1022,46,Great fit,"Love these jeans, fit and style... the wash is...",5,1,0,General,Bottoms,Jeans
21962,21962,1011,23,Wrapped in cozy,"Great skirt, easy to wear. perfect weight for ...",5,1,1,General,Bottoms,Skirts
3484,3484,1056,55,None,None,5,1,0,General Petite,Bottoms,Pants
19205,19205,1078,45,Flattering but not for work,This dress was as pretty in real life as the p...,3,1,8,General,Dresses,Dresses
13169,13169,1078,64,Fabulous!,This dress is so comfortable and looks so good...,5,1,10,General,Dresses,Dresses
21024,21024,895,64,"Pretty,pretty",I never noticed this sweater online but when i...,5,1,9,General Petite,Tops,Fine gauge
3812,3812,996,33,Xl runs small,"Would have loved this skirt, but the xl is clo...",3,1,0,General Petite,Bottoms,Skirts
20093,20093,967,32,None,None,5,1,0,General,Jackets,Jackets
4993,4993,945,69,Gorgeous! sooo soft!,Ignore the nutty negative review because this ...,5,1,2,General Petite,Tops,Sweaters
22967,22967,895,54,Very classy and subtly chic,"This a a great sweater! it is classic, but has...",5,1,1,General,Tops,Fine gauge
7706,7706,867,63,"Bulky, unflattering",I was surprised by the other reviews. expected...,2,0,4,General,Tops,Knits
18386,18386,830,58,Very versatile,I love how feminine and interesting this top i...,5,1,0,General,Tops,Blouses
11683,11683,825,42,So pretty!,Not sure where to start with this top...it's t...,5,1,0,General,Tops,Blouses
5056,5056,1095,32,Adorable and excellent quality,This is such a clean and cute printed dress an...,4,1,0,General Petite,Dresses,Dresses
12294,12294,569,46,"It's like a work of art, but sadly, not flatte...","It's like a work of art, but sadly, not flatte...",2,0,1,General,Trend,Trend
17839,17839,844,51,What a disappointment,I should have read the reviews first before or...,1,0,0,General,Tops,Blouses
21628,21628,1077,42,None,"Love this dress! it fits perfectly, is flatter...",5,1,8,General,Dresses,Dresses
9457,9457,872,48,None,Beautiful and chic. so glad i tried it on!,5,1,0,General Petite,Tops,Knits
5154,5154,881,54,Cool summer tee,I picked this top hoping that it would go with...,5,1,1,General Petite,Tops,Knits
1681,1681,860,26,Beautiful fabric!,This top is everything i wanted it to be. the ...,5,1,0,General Petite,Tops,Knits
4529,4529,863,31,None,"Nice lines, just a bit tight if you have large...",3,1,0,General,Tops,Knits
21731,21731,1033,48,In love with these,So many compliments and so comfortable--all i ...,5,1,2,General Petite,Bottoms,Jeans
7377,7377,1086,46,Gorgeous colors!,This dress is beautiful on so many levels. the...,4,1,0,General,Dresses,Dresses
9486,9486,843,32,"Beautiful top, just not perfect",I got my usual xs (i'm a 32b) and the top fit ...,3,1,1,General,Tops,Blouses
15364,15364,1083,39,None,None,5,1,0,General,Dresses,Dresses
6267,6267,927,35,Unexpectedly love it!,This vest is great. i'm wearing with my red st...,5,1,0,General Petite,Tops,Sweaters
16562,16562,1065,46,All legs jumper!,This is really a lovely jumper and looks quite...,3,0,0,General,Bottoms,Pants
19522,19522,862,37,Great 3 season top,This top will be great in 3 seasons. i can wea...,5,1,0,General,Tops,Knits
15113,15113,1025,44,None,None,5,1,0,General,Bottoms,Jeans
12227,12227,1091,41,Beautiful sweater dress,I love this dress so much that i purchased it ...,5,1,0,General,Dresses,Dresses
10514,10514,1080,40,None,None,5,1,0,General Petite,Dresses,Dresses
2876,2876,573,34,Ok,I was so excited to receive this in the mail a...,3,0,4,General Petite,Trend,Trend
14259,14259,1110,41,Unfortunate design,Construction excellent. the dress was pretty b...,3,0,2,General,Dresses,Dresses

In [72]:
df_clean["Department Name"].value_counts()

Tops        10468
Dresses      6319
Bottoms      3799
Intimate     1735
Jackets      1032
Trend         119
None           14
Name: Department Name, dtype: int64

In [73]:
df_clean["Division Name"].value_counts()

General           13850
General Petite     8120
Initmates          1502
None                 14
Name: Division Name, dtype: int64

In [74]:
df_clean["Class Name"].value_counts()

Dresses           6319
Knits             4843
Blouses           3097
Sweaters          1428
Pants             1388
Jeans             1147
Fine gauge        1100
Skirts             945
Jackets            704
Lounge             691
Swim               350
Outerwear          328
Shorts             317
Sleep              228
Legwear            165
Intimates          154
Layering           146
Trend              119
None                14
Casual bottoms       2
Chemises             1
Name: Class Name, dtype: int64

In [75]:
df_clean["Review Postitive Feedback Count"].value_counts()

0      11176
1       4043
2       2193
3       1433
4        922
5        673
6        525
7        374
8        319
9        261
10       225
11       178
12       146
14       121
13       102
15        94
17        81
16        74
18        62
19        54
20        40
23        31
21        30
22        29
25        25
28        24
26        23
24        21
27        20
30        18
       ...
49         2
46         2
55         2
58         2
66         1
50         1
64         1
94         1
48         1
98         1
78         1
82         1
59         1
93         1
69         1
87         1
71         1
54         1
89         1
108        1
117        1
122        1
77         1
84         1
68         1
52         1
56         1
61         1
99         1
95         1
Name: Review Postitive Feedback Count, Length: 82, dtype: int64

In [76]:
df_clean["Review ID"].value_counts()

2047     1
14978    1
2692     1
645      1
6790     1
4743     1
19084    1
17037    1
23182    1
21135    1
10896    1
8849     1
14994    1
12947    1
2708     1
661      1
6806     1
4759     1
19100    1
17053    1
23198    1
12931    1
8833     1
10912    1
10880    1
613      1
6758     1
4711     1
19052    1
17005    1
        ..
1370     1
3419     1
13660    1
15709    1
9566     1
11615    1
21856    1
5448     1
19779    1
17730    1
17714    1
7465     1
1322     1
3371     1
13612    1
15661    1
9518     1
11567    1
21808    1
19763    1
21824    1
5432     1
7481     1
1338     1
3387     1
13628    1
15677    1
9534     1
11583    1
0        1
Name: Review ID, Length: 23486, dtype: int64

In [77]:
df_clean.describe()

,Review ID,Clothing ID,Age,Rating,Recommended by Customer,Review Postitive Feedback Count
count,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000
mean,11742.500000,918.118709,43.198544,4.196032,0.822362,2.535936
std,6779.968547,203.298980,12.279544,1.110031,0.382216,5.702202
min,0.000000,0.000000,18.000000,1.000000,0.000000,0.000000
25%,5871.250000,861.000000,34.000000,4.000000,1.000000,0.000000
50%,11742.500000,936.000000,41.000000,5.000000,1.000000,1.000000
75%,17613.750000,1078.000000,52.000000,5.000000,1.000000,3.000000
max,23485.000000,1205.000000,99.000000,5.000000,1.000000,122.000000

In [78]:
df_clean[df_clean["Age"] >90]

,Review ID,Clothing ID,Age,Title,Review Text,Rating,Recommended by Customer,Review Postitive Feedback Count,Division Name,Department Name,Class Name
659,659,252,93,Amazing suit!,"This is by far the cutest, most glamorous one ...",5,1,3,Initmates,Intimate,Swim
6543,6543,1095,94,None,Flattering! i love how it looks like a maxi dr...,4,1,0,General,Dresses,Dresses
8327,8327,1078,99,Beachy and boho!,I love the weight of the material; sometimes c...,5,1,1,General,Dresses,Dresses
9513,9513,871,91,None,"From the website picture (in particular, the g...",5,1,15,General,Tops,Knits
10617,10617,1028,91,Pajama jeans,"I love the coh fleetwood jeans, and since i wa...",2,0,3,General,Bottoms,Jeans
10686,10686,1002,91,None,None,5,1,0,General,Bottoms,Skirts
11545,11545,949,99,None,"Great quality, i didn't expect the neck to be ...",4,1,4,General,Tops,Sweaters
14997,14997,1025,92,The only jeans you'll ever wear!,It's hard to tell how jeans will fit when shop...,5,1,2,General,Bottoms,Jeans
15802,15802,1028,91,Cut so small!,"These are the very stretchy, almost spongy, ty...",3,0,0,General Petite,Bottoms,Jeans
17578,17578,901,93,Very pretty & soft,Great quality. very versatile design and super...,4,1,0,General,Tops,Fine gauge
18036,18036,1094,94,None,Dress just did not fit will around the hips. ...,1,0,0,General,Dresses,Dresses
18563,18563,1094,94,Great dress!,"This dress is very comfortable, not itchy at a...",5,1,1,General,Dresses,Dresses
19304,19304,1103,91,I don't understand this dress,I have been continually disappointed in retail...,1,0,3,General,Dresses,Dresses

## Issue Description

"Recommended by Customer" column's type should be boolean

## Cleaning Code

In [79]:
df_clean["Recommended by Customer"] = df_clean["Recommended by Customer"].astype("bool")

## Test

In [80]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
Review ID                          23486 non-null int64
Clothing ID                        23486 non-null int64
Age                                23486 non-null int64
Title                              23486 non-null object
Review Text                        23486 non-null object
Rating                             23486 non-null int64
Recommended by Customer            23486 non-null bool
Review Postitive Feedback Count    23486 non-null int64
Division Name                      23486 non-null object
Department Name                    23486 non-null object
Class Name                         23486 non-null object
dtypes: bool(1), int64(5), object(5)
memory usage: 1.8+ MB

## Assess

## Issue Description

## Cleaning Code

## Test

# Store

Save the clean dataframes into csv files, then compress them into a zip file. After that delete the old extracted "dirty" csv files.

## File Names

In [81]:
# Zip name
zip_name = zip_name[:-4] + "_clean.zip"

In [83]:
# Csv file names
csv_file = csv_name[:-4] + "_clean.csv"

## Create CSV Files

In [85]:
# Save the dataframes as csv files
df_clean.to_csv(csv_file)

## Create the Zip File

In [88]:
# compress the csv files
with zipfile.ZipFile(zip_name, "w") as _zip:
    _zip.write(csv_file)

## Delete Old Files

In [89]:
# Delete the old extracted csv files
os.remove(csv_name)

# Source

Dataset source : www.kaggle.com